server:
    port: 9081
    context-path: /api

spring:
    devtools:
      restart:
        exclude:  static/**,public/**
    #添加RabbitMQ的配置
    rabbitmq:
      host: localhost
      port: 5672
      username: hxy
      password: hxy1

